### ISSUE TITLE
Errors when editing views on release 6.x-2.19 & 6.x-3.3

### ISSUE THREAD

**Issue by timstallmann** [d6lts/views#1]
Hi! I just installed the new security updates to views on a site I manage, and now when I try to edit an existing view to add a new field the edits fail to stick and I'm getting the following log errors:

`Declaration of views_plugin_row::options_submit() should be compatible with views_plugin::options_submit($form, &$form_state) in /sites/all/modules/contrib/views/plugins/views_plugin_row.inc on line 0.`

`Declaration of views_handler_filter::query() should be compatible with views_handler::query($group_by = false) in /sites/all/modules/contrib/views/handlers/views_handler_filter.inc on line 0.`

Is there some additional config that needs to be done in order to install the updated releases? Is anyone else seeing this error?

This is on Drupal 6.38 running PHP 5.6.13-1+deb.sury.org~trusty+3. I had previously been on views 6.x-2.18 and just verified that on that branch these errors don't appear and my views edits save successfully.

**Comment by kiwimind** [comment]
I've just installed 6.x-2.20 on Drupal 6.38 from 6.x-2.18 and can not replicate this issue. I haven't looked into what the differences are from 2.19 to 2.20.

I'm able to add a new field to an existing view's output successfully, without any errors being written to the log.

Hope that helps.

**Comment by dsnopek** [comment]
The error doesn't say which class's declaration is incompatible? I suspect it's some other contrib module that isn't declaring those functions the same as Views is, combined with a PHP settings that are making these errors fatal. That really should have been part of the error message... Did you leave it off?

Anyway, if I'm right, it's either a matter of fixing that contrib module, or changing your php.ini so that these errors aren't fatal but just appear as notices

**Comment by rmuit** [comment]
Do you have a patched version of Views 2.x running? Specifically. https://www.drupal.org/project/views/issues/396380 ? That has a patch for Views 2 floating around somewhere in the issue, which was never committed.

"views_handler::query($group_by = false)" has literally never been in Views 2.x. I see it in the history of Views 3.x - it was committed referencing issue # 396380 and then reverted (in the views_handler base class) as part of # 2411093. Because PHP7 can't handle it.

(You seem to be not the only one. Googling "views_handler::query($group_by = false)" returns a number of sites publicly spewing this notice on their pages. And hardly any other results, for me at least.   ....though that's likely to be older versions of Views 3 on PHP7 I guess.)

For anyone encountering this / getting here through a google search: the only thing you can/should do is edit your earlier patched code.
* in views_handler.inc, your definition of query() can remove the $group_by = false without any issue; the rest of your patched code will keep working.
* in views_plugin.inc, your definition should be changed from `options_submit(&$form, &$form_state)` to `options_submit($form, &$form_state)`. (  Or change  `views_plugin_row::options_submit()` in the other direction, and remember that you made that change.) This is potentially more problematic, because it can cause other things (like the panels module) to break. Unfortunately the definition of the base views_plugin method changed between Views 2 (&$form) and Views 3 ($form)... and because PHP7 cannot live with the difference, you have to take care that ALL extended methods have the same signature. (Or live with the log messages and never update to PHP8 where it's a fatal error.)

**Comment by dsnopek** [comment]
Since this sounds like the usual Views 2.x vs 3.x thing, I'm going to close this issue. But if anyone thinks this in particular needs special consideration, we can reopen it.
